### ISSUE TITLE
A question in 2016_CppCon/Coroutines Under The Covers - Gor Nishanov - CppCon 2016.pdf

### ISSUE THREAD

**Issue by yuanzhubi** [GorNishanov/await#2]
The argument n should be copied and stored in the f.frame? 

When resumed, n is still visted in function f, so it should be store in the f.frame. In another word, every stack based context storage(including the function arguments, local variables, for abi in x86) in f should be allocated in f.frame or copyed to f.frame.

**Comment by yuanzhubi** [comment]
Through the example is  that n is copied to variable i in the codes manually, I think the detail should not be ignored but specially mentioned.

**Comment by GorNishanov** [comment]
Note the difference between green and red arrows. Only the locals / arguments where a use -> definition arrow crosses as suspend point (red color on the slides), only those need to be stored in the coroutine frame.

Those where there is no path from a use to the definition that crosses a suspend point (green arrow), don't need to be stored
